{%set name = "filechunkio" %}
{%set version = "1.8" %}
{%set compress_type = "tar.gz"}
{%set hash_type = "sha256" %}
{%set hash_val = "c8540c2d27e851d3a475b2e14ac109d66c777dd43ab67031891c826e82026745" %}
{%set build_num = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/fabian/filechunkio
  # license_file: No MANIFEST.in
  license: MIT
  license_family: MIT
  summary: FileChunkIO represents a chunk of an OS-level file containing bytes data
  dev_url: https://bitbucket.org/fabian/filechunkio
  doc_url: https://bitbucket.org/fabian/filechunkio

extra:
  recipe-maintainers:
    - pmlandwehr
