travis:
  secure:
    BINSTAR_TOKEN: qs4WGxwYHLH/Bu08wQ9ZIFLhR9qa5pwv9QMysKs9k71w1SHSkeAvAbMwv9D0dtgNEwjmMMydq7bX90cqjyMQc6nIprdGDezmgBtxVQaGRleBQ5uC1ZeMq6qvO5fBS6B6K1oYwS1/3m7dBFPB46EEDJPaDfVbkcLhkNbzrP6COa6gTzCSJauHUdFSB2f5iUVxjbnRMAdOaRQ22wEH82miwgXI0twhLgXa7eaNDMXlhBZqsPGctTWIF5v602casycIzo0g9bnfExtEwTIZDWOIHvkJ9WZChsadtmIEZMhIzVXtJt1mVyLLNMVrbDaR3h6AOJozDHLmyFM4XgTY75yAvkVHEjIAKwQnMXtyOvfvNvTCRRemdn7PonZThA2rbjbwiNHMNtLgDxlyeeYHs5gKXQEIqFuadqG5qE/6xPrsBzAIVlTwC7YE+sgbDtOEkCK3IWN8VQa2hrw4G+8iIj6RlXhFPmstjlH30bVcIADs7UPVPUVj7nzjjeRXizHvsXxMpAJ5ZI48p/ubVDMjjLXajpQqX0ymoA6Aq/uD9Bvs8SlHUn/CsZ9FzrvN3S/a25Y0Xzuf2Bq6mGjCjfb5U8CnaIOrK42NmEpB7qkaDAAO7Ri8ChSdEwgCIhKO4KssDURy9rWoiMcG30Soy9CSr4KwTYd/zLtw0dMS8O4UCxSihmU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
