travis:
  secure:
    BINSTAR_TOKEN: biHpRq0U0NgfRxagRhPFBm0KjhU48iOOxLuk81tuy+Ddj290JIycu/vFbL17emCim25kHqW5PXYWuRGpikzss/uDymFj8NkhIOtaBnHXaylZGp/HKbjrDqg40vLGgwLIaCw6xlsxq/jmaSMxQbNVaxDEo6bqSx9ABuz2ERSKPe159127tRgQyaEqGnBnw8PYROeyqD704JpRPmVuO9l4o8POppBN6j1B9fx1gdktK1l16lVUv+j4TFpZ/N95wu06Tbr60XlQZhvjD5kzSdGYstn1tqJ1tWDjoh+em0fPxKDnaNulfzvPV7fwPs1aJqW0w0qED1HeXeHMa9xAzYLxY4PJ6EeE0/Fiy3zR6hW4lp5vmm3fR8tCG74Y8V9loe2FOFfNevQJK19RkXNwdZbPxQVejjK8k1ykktow7oiVBFPM84Q5VG46q3hx4zOX0mpqJRfBIQi+1aarVcQ9uitQiNNNeNwim9XXu9owtxmj9aYvTmpkb4Ir41pL4ea22fhgfeWyskmm2DUXaAynr2IyTeI9o8p8C5f3jaBhXQa+V8DgMxlRcEqv/bdy7ctUMMh4u+XWsTb4Jg4pv0sy3fWIRessJyN0e2e62bGr9FLGiIQEAzcBglSjLNYwjI/xssCGEqHxbpjy1y9c9KB1SgeNf8Jt3jR4EP0Z9htvHrChmBA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
